GET http://localhost:1234/api/comercio/?ordenar=asc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ4OWZkZDBiZTk4MTE0YjczNzM3ZDgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzI4MTI5MTksImV4cCI6MTczMjgyMDExOX0.8kN5CRYfOObEOImeo6aVqkJ3U7ni_he9lz51nFdX8Rw

###
GET http://localhost:1234/api/comercio/90 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ4OWZkZDBiZTk4MTE0YjczNzM3ZDgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzI4MTI5MTksImV4cCI6MTczMjgyMDExOX0.8kN5CRYfOObEOImeo6aVqkJ3U7ni_he9lz51nFdX8Rw

### 
POST http://localhost:1234/api/comercio HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ4OWZkZDBiZTk4MTE0YjczNzM3ZDgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzI4MTI5MTksImV4cCI6MTczMjgyMDExOX0.8kN5CRYfOObEOImeo6aVqkJ3U7ni_he9lz51nFdX8Rw

{
    "name": "Adidas",
    "CIF": "110",
    "direccion": "calle Sanse, Madrid",
    "email": "adidas@gmail.com",
    "telefono": "629382394",
    "id": 6
}

###
POST http://localhost:1234/api/comercio/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzQ4OWZkZDBiZTk4MTE0YjczNzM3ZDgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzI4MTI5MTksImV4cCI6MTczMjgyMDExOX0.8kN5CRYfOObEOImeo6aVqkJ3U7ni_he9lz51nFdX8Rw

{
    "email": "adidas@gmail.com"
}

###
PUT http://localhost:1234/api/comercio/80 HTTP/1.1
Content-Type: application/json

{
    "name": "Uber",
    "CIF": "80",
    "direccion": "calle Perales, Madrid",
    "email": "uber@gmail.com",
    "telefono": "692304293",
    "id": 2
}
###
//DELETE http://localhost:1234/api/comercio/110 HTTP/1.1
###
DELETE http://localhost:1234/api/comercio/logical/110 HTTP/1.1